my-http:
  port: 8080
server:
  port: 8443
  http2:
    enabled: true
  ssl:
    enabled: true
#    key-store: classpath:boombiubiu-cn-tomcat-0829230537.jks
    key-store: classpath:mykey.keystore
#    key-store-password: oumq
    key-store-password: omq950511
  undertow:
    buffer-size: 1024
    direct-buffers: true
    eager-filter-init: true
    io-threads: 10
    worker-threads: 80
#  servlet:
#    context-path: /aws

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    url: jdbc:mysql://myawsdb.chlbl2mzlbgt.ap-southeast-1.rds.amazonaws.com:3306/myawsdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池配置
    # 最小空闲连接数量
    hikari:
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名字
      pool-name: MyHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: cn.boombiubiu.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:log4j2/log4j2.xml
  level:
    org:
      springframework: INFO

jwt:
  # token失效时间 2h
  expired-time: 7200000
  # 签名密匙
  secret: B59D69DD4A7E48089B5871D4CD9CD2BE
  # 不需要token的路径
  exclude-path: /token/genToken|/login/login